### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wuori** [ally/ally.github.io#1]
Sorry for contacting you like this and for the interruption, but it seems like you're not using this github account anymore and I'd really like to use the name "ally", if you don't mind. 

If you're no longer using it, could you please delete it? If not, no worries, and happy coding! 

Again, my apologies for the intrusion!

**Comment by ally** [comment]
@wuori Sorry, didn't see this. I use this account a lot, mainly for private repos. Sorry!

**Comment by wuori** [comment]
@ally No worries and thank you so very much for replying!
